import mongoose from "mongoose";

/**
 * ROOM MODEL - For Couple Quiz Collaboration
 *
 * PURPOSE: Stores a "quiz room" where two people (spouses/partners)
 * can join by code and play quizzes together to understand each other.
 *
 * HOW IT WORKS:
 * 1. User A creates a room → Gets unique 6-char code (ABC123)
 * 2. User A shares code with partner via WhatsApp/text (external)
 * 3. User B joins room using that code
 * 4. Both users can now select & play quizzes together
 * 5. Quiz answers are tracked in 'quizAnswers' for later comparison
 * 6. Room auto-deletes after 24 hours if unused
 */

const roomSchema = new mongoose.Schema(
  {
    // ROOM IDENTIFICATION
    roomCode: {
      type: String,
      unique: true,
      required: true,
      uppercase: true,
      // 6-char code like "ABC123" - What couples share with each other
      // Generated by server so unique, easy to share, hard to guess
    },

    // OWNER INFO
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "user",
      required: true,
      // Which user created this room (User A)
      // Used to track who started the collaboration
    },

    // PARTICIPANTS - The two people in this room
    participants: [
      {
        userId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "user",
        },
        // User ID of each person
        name: String,
        // Display name so we know who's who
        joinedAt: {
          type: Date,
          default: Date.now,
          // When they joined - helps know who's online
        },
      },
    ],
    // Max 2 people per room (user A + user B)
    maxParticipants: {
      type: Number,
      default: 2,
    },

    // ROOM STATE
    status: {
      type: String,
      enum: ["waiting", "playing", "completed"],
      default: "waiting",
      // "waiting" = room created, waiting for partner
      // "playing" = quiz is active, both answering
      // "completed" = quiz finished, showing results
    },

    // QUIZ TRACKING
    currentQuiz: {
      type: String,
      default: null,
      // Which quiz is being played now (ID of quiz)
      // null = no quiz active, showing menu
    },

    // ANSWERS STORAGE - For comparison after quiz
    quizAnswers: [
      {
        userId: mongoose.Schema.Types.ObjectId,
        // Which person's answers these are
        answers: [
          {
            questionId: String,
            // Which question was answered
            answer: String,
            // What they answered (A/B/C/D or free text)
            timestamp: Date,
            // When they answered (needed if we time-limit)
          },
        ],
      },
    ],
    // Example:
    // User A answers Q1="A", Q2="B"
    // User B answers Q1="B", Q2="A"
    // Compare at end: Q1 they differ (A≠B), Q2 they differ (B≠A)
    // Show: "You answered differently on 2/10 questions"

    // AUTO-CLEANUP
    expiresAt: {
      type: Date,
      default: () => new Date(Date.now() + 24 * 60 * 60 * 1000),
      // 24 hours from creation
      index: { expireAfterSeconds: 0 },
      // MongoDB auto-deletes after this date (TTL index)
      // Prevents old rooms from cluttering database
    },
  },
  { timestamps: true },
);

export default mongoose.model("room", roomSchema);
